/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcmd;

import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Fran
 */
public class Fortran extends javax.swing.JFrame {
    public int n;
    
    /**
     * Creates new form Fortran
     */
    public Fortran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        InnerPanel = new javax.swing.JPanel();
        panelInputs = new javax.swing.JPanel();
        ULabel = new javax.swing.JLabel();
        LLabel = new javax.swing.JLabel();
        CoefLabel = new javax.swing.JLabel();
        CoefText = new javax.swing.JTextField();
        UText = new javax.swing.JTextField();
        LText = new javax.swing.JTextField();
        Button = new javax.swing.JButton();
        nLabel = new javax.swing.JLabel();
        nComboBox = new javax.swing.JComboBox<String>();
        nButton = new javax.swing.JButton();
        panelResults = new javax.swing.JPanel();
        ALabel = new javax.swing.JLabel();
        BLabel = new javax.swing.JLabel();
        CLabel = new javax.swing.JLabel();
        PLabel = new javax.swing.JLabel();
        AText = new javax.swing.JLabel();
        BText = new javax.swing.JLabel();
        CText = new javax.swing.JLabel();
        PText = new javax.swing.JLabel();
        PanelVectors = new javax.swing.JPanel();
        vULabel = new javax.swing.JLabel();
        vDLabel = new javax.swing.JLabel();
        vLLabel = new javax.swing.JLabel();
        vUText = new javax.swing.JLabel();
        vDText = new javax.swing.JLabel();
        vLText = new javax.swing.JLabel();
        PanelSol = new javax.swing.JPanel();
        ZLabel = new javax.swing.JLabel();
        YLabel = new javax.swing.JLabel();
        XLabel = new javax.swing.JLabel();
        ZText = new javax.swing.JLabel();
        YText = new javax.swing.JLabel();
        XText = new javax.swing.JLabel();
        MatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ULabel.setText("u =");
        ULabel.setToolTipText("u is the speed of the contaminant.");

        LLabel.setText("L =");

        CoefLabel.setText("coef =");

        UText.setToolTipText("Here write the speed (u) of the contaminant.");

        Button.setText("Calculate");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        nLabel.setText("n =");

        nComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        nButton.setText("...");
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputsLayout = new javax.swing.GroupLayout(panelInputs);
        panelInputs.setLayout(panelInputsLayout);
        panelInputsLayout.setHorizontalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ULabel)
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CoefLabel)
                            .addComponent(LLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CoefText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addComponent(Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputsLayout.setVerticalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ULabel)
                    .addComponent(UText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLabel)
                    .addComponent(LText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoefLabel)
                    .addComponent(CoefText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button)
                    .addComponent(nLabel)
                    .addComponent(nComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nButton)))
        );

        ALabel.setText("A =");

        BLabel.setText("B =");

        CLabel.setText("C =");

        PLabel.setText("Pel =");

        javax.swing.GroupLayout panelResultsLayout = new javax.swing.GroupLayout(panelResults);
        panelResults.setLayout(panelResultsLayout);
        panelResultsLayout.setHorizontalGroup(
            panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultsLayout.createSequentialGroup()
                        .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResultsLayout.createSequentialGroup()
                                .addComponent(ALabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AText))
                            .addGroup(panelResultsLayout.createSequentialGroup()
                                .addComponent(PLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PText)))
                        .addContainerGap(159, Short.MAX_VALUE))
                    .addGroup(panelResultsLayout.createSequentialGroup()
                        .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResultsLayout.createSequentialGroup()
                                .addComponent(BLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BText))
                            .addGroup(panelResultsLayout.createSequentialGroup()
                                .addComponent(CLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CText)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelResultsLayout.setVerticalGroup(
            panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALabel)
                    .addComponent(AText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BLabel)
                    .addComponent(BText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLabel)
                    .addComponent(CText))
                .addGap(15, 15, 15)
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLabel)
                    .addComponent(PText)))
        );

        PanelVectors.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        vULabel.setText("U =");

        vDLabel.setText("D =");

        vLLabel.setText("L =");

        javax.swing.GroupLayout PanelVectorsLayout = new javax.swing.GroupLayout(PanelVectors);
        PanelVectors.setLayout(PanelVectorsLayout);
        PanelVectorsLayout.setHorizontalGroup(
            PanelVectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVectorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVectorsLayout.createSequentialGroup()
                        .addComponent(vULabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vUText))
                    .addGroup(PanelVectorsLayout.createSequentialGroup()
                        .addComponent(vDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vDText))
                    .addGroup(PanelVectorsLayout.createSequentialGroup()
                        .addComponent(vLLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelVectorsLayout.setVerticalGroup(
            PanelVectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVectorsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelVectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vULabel)
                    .addComponent(vUText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vDLabel)
                    .addComponent(vDText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVectorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLLabel)
                    .addComponent(vLText)))
        );

        PanelSol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ZLabel.setText("Z =");

        YLabel.setText("Y =");

        XLabel.setText("X =");

        javax.swing.GroupLayout PanelSolLayout = new javax.swing.GroupLayout(PanelSol);
        PanelSol.setLayout(PanelSolLayout);
        PanelSolLayout.setHorizontalGroup(
            PanelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSolLayout.createSequentialGroup()
                        .addComponent(ZLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZText))
                    .addGroup(PanelSolLayout.createSequentialGroup()
                        .addComponent(YLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YText))
                    .addGroup(PanelSolLayout.createSequentialGroup()
                        .addComponent(XLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(XText)))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        PanelSolLayout.setVerticalGroup(
            PanelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZLabel)
                    .addComponent(ZText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YLabel)
                    .addComponent(YText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XLabel)
                    .addComponent(XText)))
        );

        MatButton.setText("Mathematical solution");
        MatButton.setEnabled(false);
        MatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InnerPanelLayout = new javax.swing.GroupLayout(InnerPanel);
        InnerPanel.setLayout(InnerPanelLayout);
        InnerPanelLayout.setHorizontalGroup(
            InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnerPanelLayout.createSequentialGroup()
                .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InnerPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(MatButton))
                            .addComponent(panelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelVectors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 307, Short.MAX_VALUE))
        );
        InnerPanelLayout.setVerticalGroup(
            InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnerPanelLayout.createSequentialGroup()
                .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addComponent(panelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MatButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(PanelVectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane.setViewportView(InnerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        //get the users values
        n = Integer.parseInt(nComboBox.getSelectedItem().toString());
        try{
            double u = Double.parseDouble(UText.getText());
            double l = Double.parseDouble(LText.getText());
            double c = Double.parseDouble(CoefText.getText());
            
            //calls rio program
            Rio rio = new Rio();
            rio.start(u, l, c, n);
            Iterator<String> iterator = rio.getList().iterator();
            
            //set the labels
            PText.setText(iterator.next());
            AText.setText(iterator.next());
            BText.setText(iterator.next());
            CText.setText(iterator.next());
            vLText.setText(iterator.next());
            vDText.setText(iterator.next());
            vUText.setText(iterator.next());
            ZText.setText(iterator.next());
            YText.setText(iterator.next());
            XText.setText(iterator.next());
            
            //set the mathematica sol button
            MatButton.setEnabled(true);
        }
        catch(NumberFormatException ne){
            System.err.println("Bad input...");
            JOptionPane.showMessageDialog(null, "You have to write a rigth values as inputs.",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        String nText =JOptionPane.showInputDialog(null, "n = ", 
                "How many points do you want?", JOptionPane.QUESTION_MESSAGE);
        if(Integer.parseInt(nText)>10)
            nComboBox.addItem(nText);
        nComboBox.setSelectedItem(nText);
    }//GEN-LAST:event_nButtonActionPerformed

    private void MatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatButtonActionPerformed
        //1. try to get pel
        try {
            double pel = Double.parseDouble(PText.getText());
            StringBuilder text = new StringBuilder();
            //2. Create a vector for the solutions
            double sol[] = new double[n];
            //3. Get the values
            text.append("[");
            int i=0;
            for(; i<n; i++) {
                sol[i]=-(Math.pow(Math.E,pel*(i+1)/(n+1))-1)/(Math.pow(Math.E,pel)-1)+1;
                if(i==n-1)
                    text.append(String.format("%.4f]", sol[i]));
                else
                    text.append(String.format("%.4f,", sol[i]));
                
            }
            //4. print in a joption the solutions
            
            JOptionPane.showMessageDialog(null,"The mathematicas solution is:\n "+text,
                            "SOLUTION",JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException ne){
            System.err.println("Bad input...");
            JOptionPane.showMessageDialog(null, "You have to write a rigth values as inputs.",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fortran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fortran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fortran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fortran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fortran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JLabel AText;
    private javax.swing.JLabel BLabel;
    private javax.swing.JLabel BText;
    private javax.swing.JButton Button;
    private javax.swing.JLabel CLabel;
    private javax.swing.JLabel CText;
    private javax.swing.JLabel CoefLabel;
    private javax.swing.JTextField CoefText;
    private javax.swing.JPanel InnerPanel;
    private javax.swing.JLabel LLabel;
    private javax.swing.JTextField LText;
    private javax.swing.JButton MatButton;
    private javax.swing.JLabel PLabel;
    private javax.swing.JLabel PText;
    private javax.swing.JPanel PanelSol;
    private javax.swing.JPanel PanelVectors;
    private javax.swing.JLabel ULabel;
    private javax.swing.JTextField UText;
    private javax.swing.JLabel XLabel;
    private javax.swing.JLabel XText;
    private javax.swing.JLabel YLabel;
    private javax.swing.JLabel YText;
    private javax.swing.JLabel ZLabel;
    private javax.swing.JLabel ZText;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton nButton;
    private javax.swing.JComboBox<String> nComboBox;
    private javax.swing.JLabel nLabel;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JPanel panelResults;
    private javax.swing.JLabel vDLabel;
    private javax.swing.JLabel vDText;
    private javax.swing.JLabel vLLabel;
    private javax.swing.JLabel vLText;
    private javax.swing.JLabel vULabel;
    private javax.swing.JLabel vUText;
    // End of variables declaration//GEN-END:variables
}
